# Generated by Django 4.2 on 2023-04-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date_added',
        ),
    ]
