# Generated by Django 4.1.6 on 2023-03-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_cart_id'),
    ]

    operations = [
    ]
